### ISSUE TITLE
Recomendación sobre el Manifiesto

### ISSUE THREAD

**Issue by goliveirab** [vzlajs/Manifesto#1]
En aras de hacer visible tanto en acción como en palabras lo pronunciado en el manifiesto : "sin importar su sexo....., orientación sexual", les recomiendo hacer uso de un lenguaje mas inclusivo, por ejemplo:

Todas y cada una de las personas que integren la comunidad Javascript en Venezuela, conocida cómo Venezuela.js, como colaboradores o colaboradoras nos dedicaremos a impartir y compartir conocimientos sobre este lenguaje a todas las personas interesadas en aprenderlo. Recibiremos a todas aquellas personas que deseen aportar sus conocimientos y habilidades en pro de nuestra comunidad, sin importar su sexo, apariencia física, discapacidad, condición social, campo laboral, orientación sexual, raza o credo.

Tenemos como principales propósitos:

```
Fomentar el uso de Javascript en Venezuela.
Generar documentación y material didáctico para el aprendizaje del lenguaje.
Colaborar con las nuevas comunidades que surgen en el país.
Fomentar la unión y la auto organización de nuevas comunidades.
Incentivar la colaboración y el trabajo en equipo..
```

Ninguna persona que integre esta comunidad está en la potestad de solicitar remuneración económica por impartir conocimientos y/o instruir sobre “Javascript” utilizando el nombre de “Venezuela.js” cómo organización.

**Comment by Villanuevand** [comment]
Hola @goliveirab totalmente válida tú acotación.
Por favor haz `fork` del manifesto, y realiza un `pull request` para acentar que los cambios fueron solicitados y realizados por tú persona. 

Si necesitas ayuda sobre el proceso, no dudes en hacerlo saber. 

Quedamos atentos a tus comentarios.

**Comment by X3MBoy** [comment]
Yo estoy en desacuerdo con la modificación. Ya se hace mención a todos los miembros, volver a mencionarlos como "colaboradores y colaboradoras" es redundar sin necesidad, además que hace ver que todos los miembros se dedicaran a impartir y compartir conocimientos, cuando pueden haber miembros que colaboren de otras maneras sin necesidad de involucrarse en las actividades de impartir conocimientos técnicos.

**Comment by abr4xas** [comment]
:+1:  a lo que dice @X3MBoy

**Comment by Villanuevand** [comment]
Ciertamente @X3MBoy , el manifesto usa:

> Todos y cada uno de los miembros colaboradores de la comunidad de Javascript en Venezuela.

para englobar géneros, y como bien comentas, decimos que: 

> Recibiremos a todas aquellas personas que deseen aportar sus conocimientos y habilidades en pro de nuestra comunidad.

Para recalcar que cualquier profesional es bienvenido, cuando aporta ideas en pro de nuestra comunidad, no tiene que ser desarrollador para unirsenos.

Solicitamos a @goliveirab realizar el `pull request` ya que esa es la manera "legal" de realizar modificaciones en el escrito, las cuales deben ser revisadas y aceptadas por el grupo de administradores de la organización.

**Comment by goliveirab** [comment]
CompañerOs (y entiendase la O porque solo estoy hablando con hombres) si yo dijera compañerAs se sentirian incluidos? obviamente no! 

Entiendo que el androcentrismo esta en todas y todos pero el lenguaje inclusivo no es una ofensa ni una critica, es una sugerencia. Les recomiendo leer un poco mas sobre inclusión, esta es otra sugerencia no un juicio.

Es comprensible la reacción del compañero @X3MBoy quien piensa que la O o la E hace alusión a "lo universal", compañerO la mitad de la población mundial usa la A para definirse y reconocerse.

Por otra parte, como dije antes mi comentario fue una sugerencia, no una exigencia, esto debido a que en reiteradas ocasiones en otros grupos algunos compañerOs se quejan o se preguntan sobre la poca participación de mujeres y personas sexo diversas, pero nunca se preguntan o analizan el porque, mi comentario simplemente pretendía que Uds, como comunidad naciente entendieran, de primera mano, la necesidad de visibilizar a la otra desde la palabra para la acción. 

@Villanuevand lamentandolo mucho no creo que sea adecuado que sea Yo quien haga la modificación, sobre todo porque al parecer es algo bastante delicado, es algo que uds como fundadorEs deben discutir.

Saludos!
Y espero esto sirva para entender (pensar mas profundamente) que la inclusión va mas allá de colocar "sin importar sexo, raza, credo, discapacidad, ......etc"

**Comment by Villanuevand** [comment]
Hola @goliveirab, la modificación no la harás tú, solo la propondras. 
A los administradores de Venezuela.js nos tocará analizar si se hace o no la inclusión de la modificación al documento.

Pero la manera de hacerlo es mediante una bifurcación o `fork` del proyecto, y su respectiva petición de adhesión o `pull request`. 
Te invitamos a hacer este procedimiento para solicitar formalmente que se estudien tus recomendaciones.

**Comment by abr4xas** [comment]
Voy a ponerme un poco intenso acá...

Realmente pensar que la culpa de que no existan mujeres o personas de sexo diverso en una comunidad la tiene una letra que esta en un texto cualquiera? Realmente piensas eso?

Germana, nos conocimos hace tiempo en un evento que organizaba #VaSLibre y realmente con ese poco tiempo que nos tratamos comprendí que eres una chama muy genial y espero que lo que digo no lo tomes a personal.

Sea "os", "as" aquí somos un grupo de gente reunidas por aprender algo, por compartir algo... 

Es más, propongo lo siguiente:

Cambiemos la palabra `colaboradores` por `JavaScripters`

**Comment by X3MBoy** [comment]
Ok, aprovecho la puerta y entro.

La caracterización de género para algunas cosas es absurda, no te excluyo
si te digo IngenierO, es cómo que yo me ofendiera porque me dijeras personA:

La técnico
La ingeniero
La gerente
La persona

Si dependes de una letra para definirte y conocerte, no sé ni siquiera que
puedo esperar de ti como persona.

Se despide el persono,
Eduard Lucena

El 23 de junio de 2015, 21:33, ángel notifications@github.com escribió:

> Voy a ponerme un poco intenso acá...
> 
> Realmente pensar que la culpa de que no existan mujeres o personas de sexo
> diverso en una comunidad la tiene una letra que esta en un texto
> cualquiera? Realmente piensas eso?
> 
> Germana, nos conocimos hace tiempo en un evento que organizaba #VaSLibre y
> realmente con ese poco tiempo que nos tratamos comprendí que eres una chama
> muy genial y espero que lo que digo no lo tomes a personal.
> 
> Sea "os", "as" aquí somos un grupo de gente reunidas por aprender algo,
> por compartir algo...
> 
> Es más, propongo lo siguiente:
> 
> Cambiemos la palabra colaboradores por JavaScripters
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vzlajs/vejs-manifesto/issues/1#issuecomment-114705778
> .

## 

# 

```
         Eduard Lucena
      Cel:=0424-5216478
 GNU/Linux User #403161
      Ubuntu User #8749
```

#

**Comment by goliveirab** [comment]
@abr4xas no hablo de culpa es visibilización. Existen muchas razones del porque las cifras son tan bajas en la participación de las mujeres en las TIC y mucho mas en las TIL, pero el lenguaje androcentrico,  históricamente aceptado como "normal", "natural" y "universal", no ayuda. Es comprensible que desde la perspectiva de los incluidos, es difícil ver la situación de la otra. 

@X3MBoy nuevamente, hablo de visibilización. 
Compañero Persona e Ingeniero, no tienen el mismo significado, ni hacen referencia a lo mismo. Tus argumentos realmente no sorprenden, lo llano y la soltura de ellos evidencia el desconocimiento en la profundidad epistemológica y política del problema de invisibilización de la mitad del mundo.

Después de todo esto, avancemos en la construcción, ya que el debate sin un cuerpo categorial fundamentado no aporta mas que el desperdicio del tiempo y de expectativas sobre otras formas de concepción de una ética humana. El objetivo de la sugerencia era aportar y ser complementada con otros aportes desde argumentos concebidos desde un marco filosófico.

Sin mas, mi ultima sugerencia para este grupo es un dialogo sobre la propuesta de @abr4xas :
Cambiemos la palabra colaboradores por JavaScripters

**Comment by Villanuevand** [comment]
Actualmente se esta trabajando en segunda revisión de nuestro manifesto, el cual será publicado muy pronto. 

Invitamos a todos a leerlo y hacernos llegar sus opiniones formales vías "Solicitud de Adhesión" O `Pull Request`.

**Comment by stefanmaric** [comment]
La RAE carga contra el “todos y todas”
http://www.montevideo.com.uy/auc.aspx?257854

**Comment by ajsb85** [comment]
Está bueno ese articulo sobre el sexismo en el lenguaje pero hay que buscar fuentes mas confiables de  de la propia RAE.

**Comment by stefanmaric** [comment]
En cualquier caso, Venezuela.JS es para discutir sobre JS, no sexismo ni gramática del español. No hay que perder el foco.
